# -*- coding: utf-8 -*-
"""Retail_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZVP2AUqfkQljWy168ZG-uvwfUkG3iB5b
"""

import pandas as pd
import matplotlib.pyplot as plt

# Sample dummy dataset
data = {
    'Brand': ['SuperMart', 'MegaStore', 'LocalMart'] * 4,
    'Month': ['Jan', 'Jan', 'Jan', 'Feb', 'Feb', 'Feb', 'Mar', 'Mar', 'Mar', 'Apr', 'Apr', 'Apr'],
    'Sales': [125000, 110000, 75000, 130000, 108000, 77000, 128000, 112000, 76000, 132000, 115000, 79000],
    'Avg_Price': [4.85, 4.20, 5.65, 4.90, 4.10, 5.70, 4.80, 4.30, 5.60, 4.95, 4.25, 5.75],
    'Customers': [26000, 27500, 13300, 26800, 27800, 13600, 26500, 28200, 13400, 27000, 28500, 13700]
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate total sales per brand
total_sales = df.groupby('Brand')['Sales'].sum()

# Calculate market share (%)
market_share = (total_sales / total_sales.sum()) * 100
market_share = market_share.sort_values(ascending=False)

# Plot market share bar chart
plt.figure(figsize=(8, 5))
market_share.plot(kind='bar', color=['skyblue', 'orange', 'green'])
plt.title('Market Share by Brand (Total Sales)')
plt.ylabel('Market Share (%)')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('market_share.png')
plt.close()

# Calculate average price trend per brand over months
avg_price_trend = df.pivot_table(index='Month', columns='Brand', values='Avg_Price')

# Plot pricing trend line chart
plt.figure(figsize=(8, 5))
for brand in avg_price_trend.columns:
    plt.plot(avg_price_trend.index, avg_price_trend[brand], label=brand, marker='o')
plt.title('Average Pricing Trend (Monthly)')
plt.xlabel('Month')
plt.ylabel('Average Price ($)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('pricing_trend.png')
plt.close()

print("Analysis complete. Visuals saved as 'market_share.png' and 'pricing_trend.png'.")